site_name: Deceptgold Documentation
site_url: https://docs.decept.gold/
docs_dir: content
site_dir: site
theme:
  name: material
  features:
    - content.code.copy
    - content.tabs
    - search.suggest
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
nav:
  - Home: index.md
  - CLI Reference: Commands.md
  - Installation: Installation.md
  - Architecture: Architecture.md
  - Blockchain: Blockchain.md
  - Testing: Testing.md
  - Web3 Testing: Web3_Testing.md
  - Development: Development.md
  - Contributing: Contributing.md
  - About: About.md
  - Whitepaper: Whitepaper.md
  - Rewards: Rewards.md
extra:
  generator: false